### ISSUE TITLE
var run = function update()

### ISSUE THREAD

**Issue by otajor** [crystal-seals/sick-ass-clock#48]
https://github.com/crystal-seals/sick-ass-clock/blob/master/newjs.js#L86

Possibly you have a reason for doing this, but it looks like you are creating a function called `update`, and then assigning it to a variable called `run`

**Comment by sofiapoh** [comment]
That's so we can setInterval for all the functions to run. Maybe there is a better way of doing it?

**Comment by otajor** [comment]
You have `var run = function update() {...}`

But the `update` doesn't do anything as far as I can see. Why not just do:

`function run () {...}` or `var run = function () {...}` ?

**Comment by RichAWarren** [comment]
Ah understood! Changd to `var run = function () {...}`

Thanks!
